name: Branch Build fiat publish


on:
  push:
    branches:
    - v1.31.3-1.28.4
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

jobs:
  publish-fiat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Build
        env:
          NEXUS_VERSION: 1.31.3-SNAPSHOT
        run: |
            
              cat <<EOF>> patch
            
              version = "$NEXUS_VERSION"
              group = 'io.spinnaker.fiat'
              apply plugin: 'maven-publish'

              publishing{
                   publications{
                       maven(MavenPublication){
                            groupId = 'io.spinnaker.fiat'
                            artifactId = 'NEXUSARTIID'
                            version = "$NEXUS_VERSION"
                            from components.java
                 pom {
                   name = 'NEXUSARTIID'
                   description = 'A description of my library'
                   }
                 }
              }

              repositories {
                 maven{
                 name = 'nexus'
                 url "https://nexus.opsmx.net/repository/maven-snapshots/"
                  credentials {
                    username = "${{ secrets.NEXUS_USERNAME }}"
                    password = "${{ secrets.NEXUS_PASSWORD }}"
                         }
                     }
                }
               }  
                               

              EOF
             
              ls -d */  | grep "fiat" | sed 's/\///g' > ds.txt
              
              cat ds.txt
              

              for i in $(cat ds.txt) 
              do
               sed  s/NEXUSARTIID/$i/g patch > patchnew
               cat patchnew >> $i/$i.gradle
             
              done
             
              cat -n fiat-api/fiat-api.gradle
             
              sed -e '/components\.java/ s/^#*/\/\//' -i fiat-bom/fiat-bom.gradle
                # sed  's/OP\-16464\-1.31.2\-SNAPSHOT/1.37.3\-SNAPSHOT/g' -i gradle.properties 
                 
                 cat gradle.properties 
          
                ./gradlew --no-daemon -PenableCrossCompilerPlugin=true  publish -x test
